name: C Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C/C++ environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Debug
        run: make debug

      - name: Build Release
        run: make release

      - name: Run Tests
        run: make test

